import TopMenu from '../components/layout/layout'
import {Paper} from 'material-ui'

export default () => (
  <TopMenu>
    <Paper>
      <h1>
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
        WEEEEBA WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .WEEEEBAAaaa .
      </h1>
    </Paper>
  </TopMenu>
);

